name       : libzim
version    : 8.0.0
release    : 5
source     :
    - https://github.com/openzim/libzim/archive/refs/tags/8.0.0.tar.gz : a408810c9316b56b410f6878a488f7d821c9b7eb3983e0114a4ab1a50394f7d2
homepage   : https://wiki.openzim.org/wiki/Libzim
license    : GPL-2.0-or-later
component  : programming.library
summary    : Reference implementation of the ZIM specification
description: |
    The Libzim is the reference implementation for the ZIM file format. It's a software library to read and write ZIM files on many systems and architectures. More information about the ZIM format and the openZIM project at https://openzim.org/.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(uuid)
    - pkgconfig(xapian-core)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
