name       : libzim
version    : 7.2.0
release    : 3
source     :
    - https://github.com/openzim/libzim/archive/refs/tags/7.2.0.tar.gz : 9dbcff2c0e21472a5ff7ca10c761c5ae07008a35c143df6c6274971bb536072d
homepage   : https://wiki.openzim.org/wiki/Libzim
license    : GPL-2.0-or-later
component  : programming.library
summary    : Reference implementation of the ZIM specification
description: |
    The Libzim is the reference implementation for the ZIM file format. It's a software library to read and write ZIM files on many systems and architectures. More information about the ZIM format and the openZIM project at https://openzim.org/.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - pkgconfig(uuid)
    - pkgconfig(xapian-core)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
